### ISSUE TITLE
Question about step_T

### ISSUE THREAD

**Issue by skpig** [hlzhang109/impossibility-watermark#4]
Thanks for such an elegant work on watermark attack! 
I wonder how many steps of random walk the method requires on average in your experiments? I found that the default value is set to 400.

**Comment by hlzhang109** [comment]
Thanks for reaching out! We used the default hyper-parameters as suggested in the code. Definitely the amount of steps would depend on span length, total and generated text length in different applications.

**Comment by skpig** [comment]
Thanks for your response!
